LICENSE-AGPLv3.txt
README.md

Included the AGPL-3.0 license text and updated the README to reflect on the new license terms.
**Changelog**

chore: switch to AGPL-3.0 license

---

.github/workflows/labeler-pr.yml
.github/workflows/publish.yml
Content.Client/CrewManifest/UI/CrewManifestSection.cs
Content.Client/Stylesheets/StyleNano.cs
Content.Server/CrewManifest/CrewManifestSystem.cs
Content.Shared/CrewManifest/SharedCrewManifestSystem.cs
Resources/Locale/en-US/_DV/gender.ftl
Tools/publish_multi_request.py

ported pronouns appearing in the crew manifest
I keep forgetting them and having them be more visible is nice!!
**Changelog**
:cl:
- add: ported pronoun function in crew manifest from delta-v

feat: port crew manifest pronouncs from delta-v

---

.github/workflows/labeler-pr.yml
.github/workflows/publish.yml
Resources/Prototypes/Species/arachnid.yml
Tools/publish_multi_request.py

just changes a single line to prevent selection of arachnids at character creation!

disable arachnids

---

Resources/ServerInfo/Guidebook/_starcup/StarcupShipsArticles.xml

This needs to be in a document tag or it doesn't render correctly at all in the rules popup.

fix: display ships articles with word wrapping

---

Content.Server/_DeltaV/Execution/ExecutionSystem.cs
Resources/Locale/en-US/execution/execution.ftl

ported from delta-v! there's still some weirdness like multi-pellet guns only basing execution damage off the numbers of a single bullet, but that's likely a non-critical issue

feat: gun executions

---

Resources/Prototypes/Species/human.yml
Resources/Prototypes/_DeltaV/Species/felinid.yml
Resources/Prototypes/_DeltaV/Species/harpy.yml

lets humans, felinids, and harpies use any color they want for their skintones! very simple changes
**Changelog**
:cl:
- tweak: All species now have full RGB color options for skintones

feat: enable hsv skintones for everyone

---

Content.Client/_DeltaV/AACTablet/UI/AACWindow.xaml

Localized the strings
Unlocalized strings OP please nerf 0/10
Cherry picking all day. I'm a bit of a farmer myself, you know.
It's blue so you know I didn't just steal the image from the original PR. 
AAC is now localized and you can actually see the buffer textbox.
**Changelog**
:cl: deltanedas
- fix: No more unlocalized string jumpscares in the AAC

Localise the AAC tablet UI

---

Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs

ported from goob via delta-v
Co-authored-by: BombasterDS2 <shvalovdenis.workmail@gmail.com>
Co-authored-by: BombasterDS <deniskaporoshok@gmail.com>
(cherry picked from commit 4a1acbf86315bf240f8f9c2d3995b067ea3c039b)
**Changelog**

fix: ipc causes TryStopNukeOpsFromConstantlyFailing test to fail

---

Resources/Prototypes/_DeltaV/Mail/mailDeliveries.yml

removed several mail prototypes from the random mail pool since they have been disabled
- MailCosplayArc
- MailNFCosplayMaid
- MailCosplayGeisha
- MailCosplaySchoolgirl
- MailNFCosplayNurse
- MailNFKendoKit
- MailSake
**Changelog**
:cl:
- fix: removed missing mail prototypes from the random mail pool

fix: disable missing mail prototypes

---

Content.IntegrationTests/Tests/GameObjects/Components/Mobs/AlertsComponentTests.cs

Alert Test Fix
Co-authored-by: BombasterDS <deniskaporoshok@gmail.com>
(cherry picked from commit 3e701a3359158d4539b0389a74f25bce53c95531)
AlertsComponentTest fails because of MKCs, this PR fixes that. Ported from goob.
**Changelog**

fix: change AlertsComponentTest for mkc compatibility

---

Content.Shared/Buckle/SharedBuckleSystem.Interaction.cs

cherry-picked from a delta-v commit, just a simple switch in order of operations
**Changelog**
:cl:
- tweak: You can now hug people that are buckled.

tweak: allow hugging buckled people

---

Content.Client/_CosmaticDrift/Records/UI/CharacterRecordViewer.xaml.cs
Content.Server/CriminalRecords/Systems/CriminalRecordsConsoleSystem.cs
Content.Server/_CosmaticDrift/Records/Consoles/CharacterRecordConsoleSystem.cs

forwards character records info to the criminal records console, and updates the records console to ensure setting wanted status actually works. fixes #41
**Changelog**
:cl:
- fix: Setting wanted status on criminal records console now works

fix: criminal records console bugpatch

---

Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/softsuits.yml
Resources/Prototypes/InventoryTemplates/monkey_inventory_template.yml
Resources/Prototypes/tags.yml

comments out the monkeywearable whitelist tag for all outerwear, ensuring that pun pun will no longer freeze to death by walking outside on glacier
**Changelog**
:cl:
- tweak: monkeys can now wear all outerwear! now you can help pun pun bundle up on glacier

tweak: let monkeys wear outer clothing

---

Resources/Prototypes/Entities/Mobs/Customization/Markings/scars.yml

Cherrypicked my own PR from DV that gives Vulps a bunch of scars. I ALSO BLEW UP THE FEROXI IN THIS YML CAUSE SHARKS AREN'T REAL!!!!
Vulps can get scarred too, y'know. Also using this as a learning experience on how to cherrypick and bring things from one place to another. Maints are probably going to take me out back and shoot me cause I prolly messed up somewhere idk.
Picked my PR from DV to be brought over here. It changes the scars.yml to include the vulps in scars. Also I exploded gender restricted scars except on the top surgery (can be changed at request). Also also exploded feroxi from this since they don't exist on Starcup. Also also also this cleans up the comments.
**Changelog**
:cl:
- tweak: Vulpkanin now have scars whitelisted to them.

Cherrypicking vulp scar whitelist from Delta-V

---

Content.Server/Medical/Components/HealthAnalyzerComponent.cs
Content.Server/Medical/HealthAnalyzerSystem.cs

Cherrypick of PR #3521 from Delta-V.
Moving away from a patient you've scanned with a health analyzer or medical PDA will now pause updates on the patient's condition until you move back into range, rather than stopping updates until you scan the patient again.
The way the health analyzer worked previously was a point of frustration when treating patients, requiring you to re-scan your patient every time you move more than 2.5 tiles away for any reason (retrieving medicine, letting someone else in the department, etc). This QoL feature cuts down on repeat scans and makes the treatment process smoother for everyone.
When moving out of range of a patient, updates to the health analyzer will be paused rather than stopped, and the health analyzer will continue checking to see if the patient …

feat: health analyzer reactivation

---

Content.Server/Shuttles/Components/StationCentcommComponent.cs

`StationCentcommComponent `contains a field `Map` which points to the raw map file to load for the end-of-round station. The centcomm station which gets loaded is determined by this component. This technically means that each station can have its own centcomm variant in the same way that they can have their own evac shuttle, which may be fun to know for the future. This changes the default map file to the new Syndicate Command station.
N/A
N/A
N/A
- [ x ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ x ] I have added media to this PR or it does not require an ingame showcase.
**Changelog**

fix: actually load syndicomm with the evac shuttle

---

Content.IntegrationTests/Tests/Commands/SuicideCommandTests.cs

same deal as #77, just missed a spot

fix: fix suicide test failures (again)

---

.github/workflows/build-map-renderer.yml
.github/workflows/build-test-debug.yml
.github/workflows/check-crlf.yml
.github/workflows/check-trailing-whitespace.yml
.github/workflows/lint-pull-request-title.yml
.github/workflows/test-packaging.yml
.github/workflows/validate-rgas.yml
.github/workflows/validate-rsis.yml
.github/workflows/validate_mapfiles.yml
.github/workflows/yaml-linter.yml

The lone devop with the pistol on her hip

ci: set up checks for merge queue

---

Content.Client/Parallax/Data/ParallaxLayerConfig.cs
Content.Client/Parallax/ParallaxOverlay.cs
Resources/Prototypes/_starcup/Parallaxes/planet.yml

Parallaxes now support map-lighting.
Continuance of #252 
MIT License
```
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A …
```

feat: map-lit parallaxes

---

Resources/Migrations/starcup-migrations.yml

Introduces migrations to map-out departmental economy.
People live by sharing with each other, but define themselves by what they refuse. Cultures are, in essence, systems of rejection.
**Changelog**

feat: obliterate departmental economy with migrations

---

Resources/Prototypes/Entities/Mobs/Customization/Markings/cat_parts.yml
Resources/Prototypes/Species/diona.yml
Resources/Prototypes/Species/human.yml
Resources/Prototypes/Species/moth.yml
Resources/Prototypes/Species/vox.yml
Resources/Prototypes/_DV/Species/Oni.yml
Resources/Prototypes/_DV/Species/rodentia.yml
Resources/Prototypes/_DV/Species/vulpkanin.yml

Increased marking limits in the following categories for the listed species:
**Head:**
- Diona, Vox, and Vulpekin
- Marking limit increased to 4
**Chest:**
- Diona, Humans, Oni, Rodentia, and Vox
- Marking limit increased to 4
**Arms:**
- Doptera, Humans, Oni, Rodentia, and Vulpekin
- Marking limit increased to 8
**Legs:**
- Doptera, Humans, Oni, Rodentia, and Vulpekin
- Marking limit increased to 8
**Overlay:**
- Vox and Vulpekin
- Marking limit increased to 8
Additionally, the unused Special and Tail categories have been removed from the Human species. These categories were given a limit of zero markings and clutter the marking dropdown menu, and appear to be old placeholders from a pre-Felinid era.
Species marking limits have been handled independently for a long time, partly because a …

tweak: increase marking limits

---

Resources/Prototypes/Entities/Structures/Decoration/fireplace.yml
Resources/Prototypes/Entities/Structures/Lighting/base_lighting.yml
Resources/Prototypes/Entities/Structures/Machines/Computers/arcades.yml
Resources/Prototypes/Entities/Structures/Machines/Computers/base_structurecomputers.yml
Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/Entities/Structures/Machines/anomaly_equipment.yml
Resources/Prototypes/Entities/Structures/Machines/chem_master.yml
Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Entities/Structures/Machines/seed_extractor.yml
Resources/Prototypes/Entities/Structures/Machines/stasisbed.yml
Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
Resources/Prototypes/Entities/Structures/Power/apc.yml
Resources/Prototypes/Entities/Structures/Wallmounts/WallmountMachines/station_map.yml
Resources/Prototypes/Entities/Structures/cryogenic_sleep_unit.yml

Continued from #321
- tweaked pointlight parameters for softer, more realistic lighting
---
---
---
---
---
---
---
---
---
---
---
**Changelog**
- tweak: Improved various lighting visuals for powered devices.

tweak: further improve lighting visuals

---

Resources/Prototypes/_starcup/Entities/Markers/Spawners/Mobs/animals.yml

adds some chicken spawner prototypes, one generic and one for each color of chicken
it's basically the only animal that doesn't already have a spawner, and it's nice for animal pens and such
**Changelog**
mapping asset, no cl

feat: chicken spawners

---

LEGAL.md
README.md

Due to my strong personal convictions, I wish to stress that this pull request in no way endorses a belief in the occult.

docs: licensing clarifications

---

Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml

Oops.
**Changelog**
:cl:
- fix: Paramedics now have Paramedic access.
- fix: Paramedic locker requires Paramedic access.

fix: paramedic access level fixes

---

Resources/Prototypes/_DV/Mail/mailDeliveries.yml

We've had an invalid mail prototype for five months until someone finally noticed because it crashed their local build.
**Changelog**
- fix: Removed an invalid mail option.

fix: remove invalid mail entry
