teamstarcup/starcup

Resources/Prototypes/game_presets.yml

Enable voting for Greenshift and Extended, disable voting for Deathmatch.
**Changelog**
:cl:
- tweak: enabled voting for Greenshift and Extended, disabled voting for Deathmatch

tweak: disable deathmatch, enable greenshift and extended

---

Resources/Prototypes/_DeltaV/Entities/Objects/Devices/pda.yml

not all of the checks actually ran for some reason and so I missed this. giving the admin assistants the basic pda appearance for now as a stopgap until I can decipher the appearance code

fix: uncaught admin assistant pda bug

---

Resources/Prototypes/_DeltaV/Entities/Mobs/Species/vulpkanin.yml

very small change ported from frontier, nudging up vulps' heat damage threshold so they aren't constantly overheating from everything

feat: increase vulp temperature threshold

---

Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
Resources/Prototypes/Species/moth.yml
Resources/Prototypes/Species/slime.yml
Resources/Prototypes/_DeltaV/Species/felinid.yml
Resources/Prototypes/_DeltaV/Species/harpy.yml
Resources/Prototypes/_DeltaV/Species/rodentia.yml
Resources/Prototypes/_EinsteinEngines/Species/ipc.yml

changes species heights in accordance with the drafted species heights detailed in [this document](https://docs.google.com/spreadsheets/d/1cTkaZtIL5VWPRHXHOqLIQc3b206c8YQPGMk6KKssovU/edit?gid=585732893#gid=585732893) by catty!
**Changelog**
:cl:
- tweak: Tightened base height ranges
- tweak: Made harpies, moths, and rodentia a little smaller
- tweak: Expanded minimum heights for slimes, MKCs, and felinids

feat: adjust species sizes

---

Resources/Prototypes/_DeltaV/Body/Prototypes/felinid.yml
Resources/Prototypes/_DeltaV/Body/Prototypes/harpy.yml
Resources/Prototypes/_DeltaV/Body/Prototypes/vulpkanin.yml

Fixes #36
Felinids, harpies, and vulpekin had their hands swapped. This pull request fixes that.
**Changelog**
:cl:
- fix: felinids, harpies, and vulpekin hand placements are now correct

fix: give felinids, harpies, and vulpekin the correct hand placements

---

Resources/Locale/en-US/_DeltaV/prototypes/catalog/fills/crates/medical-crates.ftl
Resources/Prototypes/_CosmaticDrift/Reactions/medicine.yml
Resources/Prototypes/_DeltaV/Catalog/Cargo/cargo_medical.yml
Resources/Prototypes/_DeltaV/Catalog/Fills/Crates/medical.yml
Resources/Prototypes/_DeltaV/Entities/Objects/Specific/Medical/healing.yml

added the missing painkiller reagent recipes, and also ported delta's painkiller crate as a logistics purchase in case there aren't any chemists available. fixes #38
**Changelog**
:cl:
- fix: Added missing chemistry recipes for stubantazine, soretizone, and agonolexyne.
- add: Added Delta-V's painkiller crate to the logistics catalog.

fix: painkiller availability

---

Resources/Prototypes/Loadouts/Jobs/Cargo/quartermaster.yml
Resources/Prototypes/Loadouts/Jobs/Command/captain.yml
Resources/Prototypes/Loadouts/Jobs/Command/head_of_personnel.yml
Resources/Prototypes/Loadouts/Jobs/Engineering/chief_engineer.yml
Resources/Prototypes/Loadouts/Jobs/Medical/chief_medical_officer.yml
Resources/Prototypes/Loadouts/Jobs/Science/research_director.yml
Resources/Prototypes/Loadouts/Jobs/Security/head_of_security.yml

establishes parity with delta-v, so department heads can have their cool capes and stuff back
**Changelog**
- tweak: mantles for command staff no longer require playtime

tweak: remove role timers from mantles

---

Content.Shared/Nutrition/Components/HungerComponent.cs
Resources/Prototypes/_DeltaV/Entities/Mobs/Species/Oni.yml
Resources/Prototypes/_DeltaV/Entities/Mobs/Species/felinid.yml
Resources/Prototypes/_DeltaV/Entities/Mobs/Species/harpy.yml
Resources/Prototypes/_DeltaV/Entities/Mobs/Species/rodentia.yml

adds the missing components to felinids, harpies, and oni, as well as increasing the hunger base decay rate per delta-v's numbers, thus indirectly fixing #37. also fixes #42
**Changelog**
:cl:
- fix: Felinids, harpies, and oni now feel hunger and thirst properly.
- tweak: The rate at which non-rodentia characters get hungry has been increased.
- tweak: Rodentia now get hungry slightly slower overall (but still 33% faster than everyone else)

fix: missing hunger/thirst components, base hunger rate

---

Resources/Prototypes/_DeltaV/Entities/Mobs/Species/felinid.yml
Resources/ServerInfo/Guidebook/Mobs/_DeltaV/Felinid.xml

comments out felinids' thieving component, which completely dodged my notice during the initial port of the species. 
**Changelog**
:cl:
- remove: Felinids no longer have the thieving gloves effect

tweak: remove thieving abilities from felinids

---

Resources/Prototypes/Entities/Objects/Materials/ore.yml
Resources/Prototypes/Entities/Structures/Storage/ore_box.yml

cherry-picks a few numerical adjustments from delta, increasing the amount of ore you find in veins as well as greatly expanding the storage of the ore box. pushing this out ahead of a more comprehensive port of delta's salvage reworks to help ease some of the more immediate balancing problems
**Changelog**
:cl:
- tweak: ore veins now provide more ore before depleting
- tweak: ore box storage greatly expanded

tweak: mining quality of life updates

---

Resources/Prototypes/Maps/Pools/default.yml
Resources/Prototypes/_starcup/Maps/Pools/default.yml
Resources/Prototypes/_starcup/Maps/glacier.yml

Added Glacier and Saltern to map voting
Low-population shifts were previously unable to vote for any map besides Reach. This adds two more maps to the pool to give players more variety.
**Changelog**
:cl:
- fix: added Glacier and Saltern to the map voting pool

fix: map vote options

---

Resources/Prototypes/game_presets.yml

Disables the SpaceTrafficControlFriendlyEventScheduler rule in Survival.
Survival already has an event scheduler that spawns Friendly, Freelance, and Hostile shuttles. Adding a second scheduler specifically for Friendly shuttles clutters the ghost roles and is unnecessary.
**Changelog**
:cl:
- tweak: removed a redundant survival event scheduler

tweak: remove redundant survival event scheduler

---

Resources/Prototypes/Entities/Stations/base.yml

Disabled various ruins in base.yml for balance/rework purposes
Disabled spawning for the following ruins:
- chunked_tcomms
- derelict
- empty_flagship
- ruined_prison_ship
- syndicate_dropship
- whiteship_ancient
- wrecklaimer
Many of these ruins are either too large, too empty, or too dangerous to keep around. The ruin syndicate_dropship in particular has a problem when spawned too close to the station due to its external turrets, which have caused issues on multiple shifts thus far.
**Changelog**
:cl:
- tweak: disabled spawning for multiple ruins

tweak: disabled multiple ruins

---

Resources/Prototypes/GameRules/unknown_shuttles.yml

Disabled a portion of the unknown shuttle spawns
This PR disables some shuttles from being spawned as a result of the Unknown Shuttles event. The following shuttles were disabled:
- TravelingCuisine
- Honki
- NTQuark
- Cruiser
- Microshuttle
- Spacebus
- LoneOpsSpawn
- Instigator
Some shuttles need reworks, others don't fit the tone of the server, and some are more appropriate as telegraphed events than random spawns.
**Changelog**
:cl:
- tweak: disabled some unknown shuttles

tweak: disabled some unknown shuttles

---

Resources/Prototypes/Maps/omega.yml
Resources/Prototypes/Maps/packed.yml

Reduced Omega and Packed minPlayers from 7 to 0
The difference between having 1-6 players and having 7 players is negligible. This change opens up more maps to be selected at low player counts, giving players more variety in map choices.
**Changelog**
:cl:
- tweak: adjusted Omega and Packed minPlayers limits

tweak: adjusted Omega and Packed minimum player limits

---

Resources/Prototypes/_DeltaV/Body/Prototypes/felinid.yml

felinids were given the reptilian stomach prototype for some reason?? so I changed it to the animal stomach, which should also fix the weird dietary restrictions they were dealing with
**Changelog**
:cl:
- fix: felinids will now be poisoned by theobromine as intended
- fix: felinids are no longer incapable of eating veggies and other such foods

fix: felinid stomach fixes

---

Resources/Prototypes/_DeltaV/Entities/Mobs/Species/Oni.yml
Resources/Prototypes/_DeltaV/Entities/Mobs/Species/felinid.yml
Resources/Prototypes/_DeltaV/Entities/Mobs/Species/harpy.yml
Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/silicon_base.yml

resolved another uncaught error as a result of the change in parent prototype for felinids, harpies, and oni. also uncommented the carriable component for mkcs now that it's no longer in conflict
**Changelog**
:cl:
- fix: felinids, harpies, oni, and mkc's can be carried

fix: add missing carriable components

---

Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml
Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/chemvend.yml

Changed starting items in some jobs' lockers and machines
Added the following items to the following lockers / machines:
- Insulated Gloves -> Atmos Tech's locker
- Magboots -> Atmos Tech's suit storage locker
- Mini Jetpack -> Salvage Specialist's locker
- Jug (Welding Fuel) -> ChemVend
Removed the following item from the following locker:
- Fire Extinguisher -> Salvage Specialist's locker
Atmos Techs should have insuls and magboots. Salvage is a painful experience at roundstart without propulsion. Chemists need welding fuel, and maps typically don't provide it to them. None of these roles are made more engaging by lacking this equipment.
Fire extinguishers were removed from the Salvage Specialist's locker as they were intended to be a pre-jetpack method of propulsion, and thus are no …

tweak: adjusted some jobs' roundstart gear

---

Resources/Prototypes/GameRules/meteorswarms.yml

minimumPlayers for the Minor and Major Space Dust events have been increased from 0 -> 10.
Low player counts have difficulties dealing with the amount of damage dealt by Space Dust meteor events. Increasing their minimum player requirements up to 10 will hopefully help ensure that at least one engineer (if not two) are on board to address the damage they cause.
**Changelog**
:cl:
- tweak: increased the minimum player requirements for space dust events

tweak: meteor event minimum player increase

---

Content.Server/StationEvents/Components/RampingStationEventSchedulerComponent.cs
Content.Server/StationEvents/RampingStationEventSchedulerSystem.cs

Changes variables and formulas found in the RampingStationEventScheduler used by Survival to reduce the rate of events to a level more appropriate for our server. Additionally, the formulas for MaxChaos and EndTime were simplified for readability.
Upstream's default settings for Survival are designed for a chaotic server with an average round time of 90 minutes. Our server favors a more slow-paced approach and longer round times, and these changes seek to strike a balance that fits those goals while still putting pressure on the players to adapt and handle an ever-escalating pace of events.
MaxChaos and EndTime formulas were both changed from an x - x/4 and x + x/4 format to equivalent percentage multipliers (x * 0.75 and x * 1.25 respectively) to simplify the formulas, improve …

tweak: ramping event scheduler adjustments

---

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml

Chief Engineer, Head of Security, Quartermaster, and Research Director will now have spare IDs in their lockers.
Previously, only the Captain and Head of Personnel had spare IDs in their lockers. This change makes promotions and theft-induced ID replacements less time-consuming and gives antagonists another potential route to gain departmental access.
**Changelog**
:cl:
- tweak: added spare IDs to department head lockers

tweak: added spare IDs to department head lockers

---

Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml

Added the security jetpack to security suit storage units
Without jetpacks, Security is dead in the water out in space. Giving them mobility outside the station enables them to perform search-and-rescue operations, pursue antagonists into space, and search for contraband and threats in unconventional locations if necessary. This also saves Cargo the trouble of ordering multiple jetpack crates per shift.
**Changelog**
:cl:
- tweak: added security jetpacks to sec suit storage units

tweak: added jetpacks to sec suit storage units

---

Content.IntegrationTests/Tests/Commands/SuicideCommandTests.cs

comments out an offending line from SuicideCommandTests because mkcs don't work in the way the test expects. should hopefully solve our build errors

fix: fixes suicide command test failure

---

Resources/Prototypes/Catalog/Fills/Boxes/emergency.yml

Added a space medipen to the survival box contents.
Players didn't have a way to respond to unexpected spacings, which could lead to a swift death if they got caught. This gives them a single-use medipen that will at least give them time to get out a warning or attempt to get back into a pressurized area.
**Changelog**
:cl:
- tweak: added space medipens to survival boxes

tweak: added space medipens to survival boxes

---

Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml

engineers with the short-sighted trait no longer have to switch between glasses as often
**Changelog**
:cl:
- tweak: engineering goggles now give +70% vision correction

tweak: engineering goggles now give +70% vision correction

---

Resources/Prototypes/Catalog/Fills/Items/belt.yml

Janitors' belt will now spawn with a trashbag rather than a bar of soap.
Janitors don't really use soap often, especially in early game, while the trashbag is a critical tool they can start using from the moment they spawn in Arrivals.
**Changelog**
:cl:
- tweak: removed Soap from ClothingBeltJanitorFilled
- tweak: added Trashbag to ClothingBeltJanitorFilled

tweak: swapped janibelt's soap for trashbag

---

Resources/Locale/en-US/_DeltaV/preferences/loadout-groups.ftl
Resources/Prototypes/Loadouts/loadout_groups.yml
Resources/Prototypes/Loadouts/role_loadouts.yml
Resources/Prototypes/_DeltaV/Loadouts/Jobs/Medical/chemist.yml
Resources/Prototypes/_DeltaV/Loadouts/Jobs/Medical/medical_doctor.yml
Resources/Prototypes/_DeltaV/Loadouts/Miscellaneous/scarfs.yml
Resources/Prototypes/_DeltaV/Loadouts/Miscellaneous/trinkets.yml
Resources/Prototypes/_DeltaV/Loadouts/loadout_groups.yml
Resources/Prototypes/_DeltaV/Loadouts/role_loadouts.yml
Resources/Prototypes/_starcup/Loadouts/Miscellaneous/trinkets.yml

I ported over Delta-V's scarf loadouts for various jobs, as well as their gold and silver ring trinkets. I also added the handheld station map to trinkets and added a bunch of pride/syndie scarves to those loadouts.
The scarves and rings enhance player customization, and the map greatly improves accessibility for new players, blind characters, and anyone on an unfamiliar map.
**Changelog**
:cl:
- Tweak: Scarves can be selected for most job loadouts including lots of pride/syndie flags.
- Tweak: Added silver gold ring trinkets and a handheld station map trinket.
- Tweak: Security Cadets can now choose between a mime beret and a basic helmet.

Tweak: add loadout scarves and trinkets

---

Content.Server/StationEvents/Components/GasLeakRuleComponent.cs
Content.Server/StationEvents/Components/VentClogRuleComponent.cs
Content.Server/StationEvents/Events/GasLeakRule.cs
Resources/Prototypes/GameRules/events.yml

Adjusted several events' variables for balance purposes
Changed the event weights, minimum player requirements, earliest start times, and reoccurrence delays for several events.
Added reoccurrence delays and maximum occurrence limits to some events. 
Adjusted the duration of the Solar Flare event.
Removed the spark chance from the GasLeak event.
Removed ephedrine from the list of safe chemicals that VentClog events could use.
Disabled the MimicVendor and WizardSpawn events until further notice.
Upstream has a decidedly more fast-paced and chaotic environment, and we want to tone that down a bit and ensure that dangerous events don't happen to early or too frequently, disruptive events don't have a chance to reoccur immediately after they're finished, and safer events can occur at lower …

tweak: basic calm and antag event rebalancing

---

Resources/Prototypes/GameRules/roundstart.yml

Revolutionaries and Zombies game modes now require more players. Wizard game mode is now fully disabled.
Revs are a game mode that targets command directly, but with a minimum player count of 15 you might only have one or two command players if any. Upping the minimum player count will hopefully ensure more interesting rounds.
Zombies are best on stations with moderate player counts or higher, and at 20 players the event runs the risk of both being too short-lived and too boring. Updating the minimum player count will ensure these rounds are more exciting.
Wizards are frankly extremely broken and cause far too much chaos in their current state. If you give free agents access to abilities that cause mass structural damage, instantly kill targets without counterplay, and completely disrupt …

tweak: wizards removed, minPlayers increased for revs + zombies

---

Resources/Locale/en-US/datasets/figurines.ftl
Resources/Prototypes/Datasets/figurines.yml

Changes figurine voice lines to fit intended server culture (now updated to include recent upstream additions)
Removed and replaced many figurine voice lines, and added many new voice lines to those with a small list of options.
The lines that figurines say when used are largely references to a more chaotic culture that we would like to leave behind as we develop our own community and establish expectations of behavior. To that end, many of the old figurine lines have been removed (references to security abusing their power and mistreating prisoners, greytiders being assholes that antagonize security, low-effort jokes about making meth/weed, etc) and replaced with lines more appropriate for the server culture we would prefer to see here on starcup.
As an added bonus, many figurines have …

tweak: updated figurine voice line overhaul

---

Resources/Prototypes/Catalog/Fills/Boxes/emergency.yml

Adds the space medipen to all non-basic survival boxes (including nitrogen boxes, job-specific boxes, and syndicate boxes)
Replaces nutribricks and non-standard food items with PSBs to make room for space medipens (sorry, mimes)
Space medipens were originally added to the basic survival box, but they were intended to be added to all survival boxes. This PR aims to correct that mistake by actually adding the space medipen to all non-silicon survival boxes.
In order for the space medipen to fit in many survival boxes, their nutribricks had to be replaced with PSBs. This also includes survival boxes with different nonstandard 2x1 foods (mostly mimes). In the future, I would love for survival box contents to be filled out based on what the player wants to start with, but that is outside the …

tweak: add space medipen to more survival boxes

---

Resources/mapping_actions_alarms.yml
Resources/mapping_actions_disposals.yml
Resources/mapping_actions_pipes.yml
Resources/mapping_actions_power.yml
Resources/mapping_actions_shuttles.yml
Resources/mapping_actions_starcup.yml

Ported Delta-V's custom mapping action preset files, then removed or replaced entities which don't exist on starcup, added new entities to presets that were lacking in utility, and reorganized action button layout for improved workflow.
The default mapping_actions.yml file used upstream is far too broad and covers a wide range of options that are _broadly_ useful, but which don't do a good job providing a tailored list of readily-accessible actions for mappers. Delta-V's custom action preset files divide the main mapping actions into multiple smaller, more focused preset files, allowing the user to load up presets for a specific task such as setting up power, lights, pipe networks, and more. Over time, I would like to add more presets to expand on these options.
**Changelog**
:cl:
- add: …

add: port of Delta-V mapping action presets

---

Resources/Maps/_starcup/Shuttles/SYND_EvacShip.yml

- Added LV Cables to ensure all thrusters were powered
- Replaced medbay's hospital curtains with open variants
- Removed a component on a medbay door that caused it to open when the shuttle was initialized
Minor bug fixes and improvements
Remember to extend your LV Cable networks, folks.
**Changelog**
:cl:
- tweak: ensured all thrusters had power on SYND_EvacShip
- tweak: made medbay's hospital curtains opened by default on SYND_EvacShip
- tweak: stopped medbay's airlock from opening on shuttle arrival on SYND_EvacShip

tweak(map): minor SYND_EvacShip fixes

---

Resources/ConfigPresets/Build/development.toml

sets the server config option for random characters to false, so you can be allowed to spawn in with specific characters and test the functions thereof. this made trying to test loadouts a major pain and I'm not entirely clear on whether it's more helpful to us right now so I figure it should be switched back off

tweak: disable random characters in dev environment

---

Content.Client/VendingMachines/UI/VendingMachineMenu.xaml.cs
Content.Client/VendingMachines/VendingMachineBoundUserInterface.cs
Content.Server/VendingMachines/VendingMachineSystem.cs
Content.Shared/VendingMachines/SharedVendingMachineSystem.cs
Content.Shared/VendingMachines/VendingMachineComponent.cs

This fix addresses an inability to save post-init maps with vending machines.

fix: declare data definition for VendingMachineInventoryEntry

---

Resources/Prototypes/Tiles/floors.yml

We need this to render snow weather outside on Glacier station. The weather system at this point is very incomplete and could use a lot of dedicated care of its own. We don't have any means to explicitly render weather over a tile like we can explicitly block it, so this change is an ad-hoc "better-case" change.

fix: render weather over steel herringbone tiles

---

Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml

Winter coats currently negate 90% of cooling on their wearer. This change decreases that negation to 50%.
This means...
* For humans, a winter coat alone does not provide enough insulation to survive forever in the cold on Glacier station. It should take around five minutes before the player begins to take damage... at a rate of about 0.02 cold damage per second.
* For vulpekin, a winter coat alone is just fine. On Glacier station, their body temperature sinks no lower than about 257 K. They do not take damage at this temperature.
* For MKC, a winter coat is exceptionally sufficient. I don't believe their body temperature even drops below zero. No damage.
Other species are untested. I would expect humans to have the least cold protection, so any issues that crop up from this shouldn't be …

tweak: nerf cold protection of winter coats

---

Resources/Locale/en-US/_starcup/research/technologies.ftl
Resources/Prototypes/Recipes/Lathes/Packs/cargo.yml
Resources/Prototypes/Recipes/Lathes/Packs/engineering.yml
Resources/Prototypes/Research/industrial.yml
Resources/Prototypes/_starcup/Recipes/Lathes/Packs/cargo.yml
Resources/Prototypes/_starcup/Research/industrial.yml

- Removes fultons and fulton beacons from the Tier 2 Industrial tree research tech Advanced Tools
- Adds a new Tier 1 Industrial tree research tech, Aerial Extraction, which costs 5000 research points and unlocks fultons and fulton beacons.
Currently, salvage has a hard time getting access to fultons and fulton beacons. They either need to find them as loot during the course of their work - entirely reliant on RNG - or they need to wait for Science to finish researching Advanced Tools, and as a Tier 2 research technology that can take some time.
This change seeks to make fultons and fulton beacons accessible earlier in the shift by making them a unique Tier 1 Industrial tree research tech, cutting the time it takes for Science to get access to fulton technology by what is hopefully a …

add: adds fultons + beacons as a T1 industrial research

---

Content.Client/UserInterface/Systems/Storage/StorageUIController.cs

You know how sometimes you pick up an item and go to use it, but no matter how hard you try to avoid it, it always goes back to your inventory *rotated?*
Yeah, this makes that not happen anymore.
Friction level: 10
Effort level: 1
You will never have to spam right click every single time you move something back into your storage ever again.
The original bit of relevant code was something like this (with my explanatory comments added):
```cs
// <-- You have something in your hand and you right-clicked (or whatever your rotate key bind is)
DraggingRotation = (DraggingRotation + Math.PI / 2f).GetCardinalDir().ToAngle();  // <-- Rotate placement angle by 90 degrees
if (DraggingGhost != null)
DraggingGhost.Location.Rotation = DraggingRotation;  // <-- If you were dragging the item in your …
```

fix: no longer rotate held items unless hovering over a storage window

---

Content.Client/_starcup/OrientationHint/OrientationHintSystem.cs
Content.Shared/Interaction/SharedInteractionSystem.cs
Content.Shared/_starcup/OrientationHint/OrientationHintComponent.cs
Resources/Prototypes/_starcup/Entities/Structures/curtains.yml

adds directional window curtains, which can only be opened from one side
also adds the OrientationHint component and system, which generalizes the examine-to-show-direction functionality of e.g. teg circulators and turnstiles.
a curtain that can be opened from outside of the station as easily as it can be closed from inside it is a complete value cancellation
allows medical to have curtains on the window instead of taking up a full tile of space
curtains already have a WallMount component but are configured for 360 degrees. this change adds new entity prototypes for each existing curtain that drops this angle to 90 degrees, effectively making them direction-dependent for interactions.
this pull request also adds a new component/system pair for generalizing client-side directionality hints …

feat: directional curtains

---

Content.Client/Light/AmbientOcclusionOverlay.cs
Content.Client/Light/EntitySystems/PlanetLightSystem.cs
Content.Client/Light/RoofOverlay.cs
Content.Shared/CCVar/CCVars.Lighting.cs

Early merge of `https://github.com/space-wizards/space-station-14/pull/38276`
> Most 13 servers have some form of AO.
> 
> Want to add some more CVARs for tweaking it. At the moment it draws to the entity render target rather than lighting as well, plus it also shows in space which may not be ideal and may need stencilling?
> 
> Also want to add it to graphics too.
Without:
With:
**Changelog**
:cl:
- add: Included an early merge of wizden's partial ambient occlusion lighting.

feat: add wall ambient occlusion [early merge]

---

Resources/Locale/en-US/_starcup/preferences/loadout-groups.ftl
Resources/Prototypes/Loadouts/role_loadouts.yml
Resources/Prototypes/Roles/Jobs/Civilian/clown.yml
Resources/Prototypes/_starcup/Loadouts/Jobs/Civilian/clown.yml
Resources/Prototypes/_starcup/Loadouts/loadout_groups.yml

this introduces a new mask loadout group for clowns, introducing a variety of alternatives (mostly the various animal masks) to the standard clown mask—or the option to not use a mask at all!
although there are a few alternate costumes available for the clown, you're always stuck wearing the same mask, which can be rather unflattering for some getups and may not be condusive to the kind of clownery people want to get up to! this not only changes that, but encourages this variety by supplying a multitude of alternatives
**Changelog**
:cl:
- tweak: clowns can now select from a variety of different masks in their loadout!

tweak: customizable clown masks

---

Resources/Prototypes/_DeltaV/Entities/Structures/Machines/mailTeleporter.yml

Removed chance for the Mail Teleporter to generate priority mail, meaning mail that penalizes Couriers for delivering it late will no longer naturally spawn.
The Priority label can still be spawned manually (mailto [playerid] [containerid] false true), and it may be useful now in clarifying when mail is actually important, such as the ACO receiving their new ID.
Priority mail is generally a source of needless stress, and it disincentivizes the crew from leaving the mailbox on, which limits curators' chances to send specialized mail deliveries.
Its intention was clearly to offer Couriers some extra "challenge", but forcing a breakneck pace only limits Couriers' opportunities to roleplay and interact in a "non-viable" manner. Being penalized because the intended recipient has gone …

tweak: removed priority mail

---

Resources/Prototypes/_DeltaV/Entities/Mobs/Customization/Markings/rodentia.yml

Gave harpies access to rodentias' bat ear and bat nose markings, plus the short tail.
Harpies have bat wings! It feels nice to give them the option of bat facial features. They already get the option of feathered ear tufts, after all, so there's precedent for harpies having _birdy_ facial features.
Just added Harpies to a few prototypes in the Rodentia file.
**Changelog**
:cl:
- tweak: Gave Harpies access to Rodentia's bat markings

tweak: give harpies access to rodentia bat markings

---

Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml

Fixes #151
**Changelog**
:cl:
- fix: Atmos techs with alternate job titles will no longer spawn with a second PDA.

fix: atmos techs with alt titles don't get two pdas

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/wallmed.yml

Security should be encouraged to be first responders. They care about the crew safety first. Giving them things like bolas, easier to access helmets, and e-pens should incentivize them to be safer and keep crit crew stable. NanoMeds sporting e-pens is mainly QoL for paramedics or general medbay emergencies.
**SecTech has gained:**
- Bolas
- Helmet
- Emergency medipens
- Unfilled EMT belt. Filled EMT belt if you hack it
**Both versions of NanoMed gained:**
- Emergency medipens
All YML in the respective vending machines.
Image of a hyper realistic vending machine here.
:cl:
- add: Added bolas, EMT belts (filled belt if hacked), emergency medipens, and helmets to the SecTech! NanoMeds now also carry a few emergency medipens.

Sec and Med vend QoL Ops: Add new sec and EMT gear to SecTech, e-pens to Med vend

---

Content.Server/GameTicking/Commands/DelayStartCommand.cs

Now there's a way to deal with the delayed start round timer being too long by delaying it with negative seconds.
single bit change
**Changelog**
:cl:
- fix: The `delayroundstart` command can now take a negative number of seconds.

fix: allow delaying round start by negative time

---

Resources/Maps/_starcup/byoin.yml

Three fixes/tweaks for Byoin station.
**Changelog**
:cl:
- tweak: Byoin: Swapped curtains in janitor closet, chief medical officer's office, dorms, psych for directional curtains.
- fix: Byoin: Inserted anomaly spawn blockers to the burn chamber and far end of the salvage arm.
- fix: Byoin: Restored missing lathes to engineering, cargo, and science.
- fix: Byoin: Replaced missing light fixtures in the AI core.
- fix: Byoin: Replaced all 'epistemics' references to 'science.'

tweak(map): general fixes for byoin

---

Resources/Prototypes/GameRules/events.yml

Increases the minimum time between Power Outage events from 5 -> 9 mins
The PowerGridCheck event lasts for 1-2 minutes and completely disrupts progress on a variety of jobs during that period, and testing the delay we originally added in conjunction with Survival's reduced time between events has shown that a 5-minute delay is not long enough to prevent frustration from building amongst the crew. This is admittedly a bandaid fix for now - what we really need is a wider variety of low-population station events for the scheduler to choose from, otherwise it may simply spawn more anomalies / artifacts instead.
**Changelog**
:cl:
- tweak: the PowerGridCheck event now has a 9-minute delay before it can run again

tweak: increase power outage event reoccurence delay

---

Resources/Locale/en-US/_starcup/job/job-names.ftl
Resources/Prototypes/_DeltaV/Loadouts/loadout_groups.yml
Resources/Prototypes/_starcup/Entities/Objects/Devices/pda.yml
Resources/Prototypes/_starcup/Entities/Objects/Misc/identification_cards.yml
Resources/Prototypes/_starcup/Loadouts/Jobs/Civilian/bartender.yml

prompted by #164, adding a senior bartender alt job title and corresponding pda. teeeechnically ported from impstation, but their implementation of the job is different enough from ours that I thought it appropriate to go in our namespace.
just adds a senior bartender roletimer (52 hours as bartender), pda, job title, and associated loadouts
**Changelog**
:cl:
- add: especially venerable bartenders now have a senior job title available in their loadout

feat: senior bartender roletimer and pda

---

Resources/Prototypes/_DeltaV/Species/felinid.yml
Resources/Prototypes/_DeltaV/Species/rodentia.yml

The height nerf has arrived. Rodentia and felinids will now be _slightly_ taller. Slightly. More specifically, felinids will be somewhat taller on average and rodentia will have a taller minimum height.
This PR is a proposal, not a demand. Whether or not we want this nerf is up to us and the community, but I will stress that skittermice are going to be shorter than rodentia, so making rodentia too short does create problems. I just want to get the "nerf" on the table so we can review it more effectively.
Below are rodentia at minimum and max height, plus a human. The first three are for the current heights, the latter three are post-change.
Felinids are changed relatively similarly, albeit with a slightly higher "high". I wish I'd gotten images for them, too, but my computer is unhappy …

tweak: upped felinid and rodentia height a tidge

---

Resources/Prototypes/Entities/Mobs/Customization/Markings/undergarments.yml
Resources/Prototypes/_DeltaV/Entities/Mobs/Customization/Markings/makeup.yml
Resources/Prototypes/_DeltaV/Species/Oni.yml
Resources/Prototypes/_DeltaV/Species/felinid.yml
Resources/Prototypes/_DeltaV/Species/harpy.yml
Resources/Prototypes/_DeltaV/Species/rodentia.yml
Resources/Prototypes/_DeltaV/Species/vulpkanin.yml
Resources/Prototypes/_EinsteinEngines/Species/ipc.yml

Up until now, only the core species have had access to the Upstream underwear markings. This has been fixed. Now, everyone but harpies will be able to wear undershirts and sports bras!
Additionally, added Rodentia to the whitelist for makeup markings! That's to say, blush, lips, and nail polish. Harpies get blush, too. <3
The omissions were not deliberate to begin with, just a mishap of timings and many downstreams having their own alternative underwear systems.
Sadly, harpies will not be able to wear underclothing (or headcoverings, incidentally) until someone figures out the layering issues for it with the wings.
I was tempted to give MKCs blush, but I held off for now. For now.
**Changelog**
:cl:
- tweak: Added Felinids, Vulpekin, Rodentia, and MKCs to the undergarments whitelists.
- …

tweak: gave more species undergarments/makeup

---

Resources/Prototypes/_DeltaV/Entities/Objects/Specific/Mail/mail.yml

Just a quick bug fix for https://github.com/teamstarcup/starcup/pull/142 so it actually blocks all priority mail and no parcel prototypes override that.
**Changelog**
:cl:
- fix: removed priority mail chance from prototypes

fix: remove priority mail chance from mail prototypes

---

Resources/Prototypes/_DeltaV/Entities/Mobs/Species/rodentia.yml
Resources/Prototypes/_DeltaV/Entities/Mobs/Species/vulpkanin.yml
Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/silicon_base.yml

Set up undergarment layers for rodentia, vulpekin, and mkcs.
**Changelog**
:cl:
- fix: Undergarments now render correctly for rodentia, vulpekin, and MKCs.

fix: render undergarments below clothes

---

Resources/Locale/en-US/_starcup/reagents/meta/toxins.ftl
Resources/Prototypes/Reagents/Consumable/Drink/alcohol.yml
Resources/Prototypes/Reagents/Consumable/Drink/drinks.yml
Resources/Prototypes/Reagents/Consumable/Drink/soda.yml
Resources/Prototypes/Recipes/Reactions/drinks.yml
Resources/Prototypes/_DeltaV/Reagents/Consumable/Drink/alcohol.yml
Resources/Prototypes/_DeltaV/Reagents/Consumable/Drink/drinks.yml
Resources/Prototypes/_starcup/Reagents/toxins.yml

tweaks the amount of ethanol many cocktails and other drinks produce on metabolism, and adjusts the ratios on a couple of cocktails. also adds a new reagent, caffeine, which is functionally identical to theobromine in all but name, and distributes the two reagents across a few drinks that probably ought to have them.
a lot of ethanol contents in this game don't make much sense. why does xeno basher magically acquire twice the ethanol content of its component drinks? why does a manhattan have nearly a quarter of the ethanol of whiskey despite being two-thirds whiskey by volume? why is a black russian just as alcoholic as vodka despite there being something besides vodka in it?
to remedy this, I've gone through every mixed drink in the game and calculated their ethanol content based on how …

tweak: drink adjustments (alcohol, coffee, etc)

---

Content.Server/Forensics/Components/FiberComponent.cs
Content.Server/Forensics/Systems/ForensicsSystem.cs

port of ["Unique glove fibers"](https://github.com/DeltaV-Station/Delta-v/pull/1455) from delta-v, giving each glove a unique fiber id similarly to fingerprints. notably you can't actually scan a glove's fingerprints directly due to weird refactoring stuff that happened since this was implemented, but this needs to be out by tomorrow afternooon and is technically workable so we can address that later
forensics are already hard enough and having gloves be utterly unrecognizable from one another on the forensic scanner just makes it harder
**Changelog**
:cl:
- add: gloves now have unique fiber IDs

feat: unique glove fibers

---

Resources/Prototypes/_starcup/Entities/Objects/Consumable/Food/Baked/cake.yml

fixes a typo leading to imitation chocolate cake producing slices of real chocolate cake when cut
**Changelog**
:cl:
- fix: imitation chocolate cake no longer splits into slices of real chocolate cake when cut

fix: imitation chocolate cake slices properly

---

Resources/Prototypes/Entities/Mobs/Species/vox.yml

vox were missing the component necessary to be able to carry them. oops!
**Changelog**
:cl:
- fix: vox can now be carried like all other species

fix: make vox carriable

---

Resources/Prototypes/Entities/Objects/Materials/Sheets/other.yml
Resources/Prototypes/_DeltaV/Entities/Objects/Specific/Medical/healing.yml

oilpacks and plastic sheets now won't be consumed to no effect. this fixes #224 
**Changelog**
:cl:
- fix: using plastic or oilpacks on MKCs with brute or burn damage respectively will no longer uselessly consume the item

fix: prevent useless application of healing items for mkcs

---

Resources/Prototypes/Entities/Objects/Tools/cable_coils.yml
Resources/Prototypes/_DeltaV/Entities/Objects/Specific/Medical/healing.yml

includes a few features found in ["IPC Adjustments - Better cables, Modified Bloodstream"](https://github.com/DeltaV-Station/Delta-v/pull/3918) from delta-v, making cables more effective and omnipatches heal radiation
the omnipatch thing just makes sense—it's an OMNIpatch—and cables are currently way too ineffective for their availability.
**Changelog**
:cl:
- tweak: cables now heal MKCs twice as effectively
- feat: omnipatches now also heal radiation damage

tweak: mkc healing buffs

---

Resources/Prototypes/_EinsteinEngines/Species/ipc.yml

lets mkcs change their hair color to anything instead of being forced to match their skintone
there's no reason for the hair color to be locked, right? plus you can change the color of each part of the body anyways, so "skin color" kinda doesn't apply anyways
**Changelog**
:cl:
- tweak: mkc hair can now be colored independently of skintone

tweak: custom mkc hair color

---

Resources/Prototypes/_starcup/Loadouts/loadout_groups.yml

some of our loadout groups had `minLimit: 0` lines erroneously applied, which allowed things like service workers spawning in with no jumpsuits, which is obviously less than ideal
**Changelog**
:cl:
- fix: loadouts have been corrected to prevent certain jobs from spawning without essential clothes

fix: loadout bugfixes

---

Resources/Prototypes/Reagents/Consumable/Drink/alcohol.yml
Resources/Prototypes/Recipes/Reactions/drinks.yml

pina coladas snuck by unnoticed in #204, so I adjusted their recipe and alcohol content. I also had another look at the moscow mule and gin fizz's recipes and changed those too
not only is pina coladas being as alcoholic as rum despite barely having any rum insane, the ratios are also completely wild. no shot you're putting the same amount of lime juice as rum into a pina colada. that's batshit
I also realized the moscow mule and gin fizz's recipe was similarly insane. 4:1 vodka to ginger ale for the moscow mule!! are you kidding me!! and why the hell are you making a gin fizz with lime juice! you make those with lemon! the flavor text literally describes it as lemony!
**Changelog**
:cl:
- tweak: the moscow mule, gin fizz, and pina colada have had their recipes and ethanol content …

tweak: assorted drink adjustments I missed

---

Resources/Prototypes/_starcup/Catalog/uplink_catalog.yml

whoops, there was an extra line that was causing the thieving gloves to display twice in the uplink! I removed that, then found a couple of other small things I fixed too
**Changelog**
:cl:
- fix: thieving gloves no longer appear twice in the uplink
- fix: the nanotrasen balloon is now properly named in the uplink
- fix: the nanotrasen deck box now appears in the uplink as intended

fix: small traitor uplink fixes

---

Content.Server/_EE/Silicon/Death/Systems/SiliconChargeDeathSystem.cs
Resources/Prototypes/Entities/Objects/Materials/Sheets/other.yml
Resources/Prototypes/_DV/Entities/Objects/Specific/Medical/healing.yml

- the event that applies forcesleep to mkcs on low-power mode needed to be refactored for the status effect changes. fixes #264 and #243
- it turns out that if you try to apply healing to a damage group a species's damage container doesn't have it'll get upset so oilpacks and plastic sheets have caustic as a dummy heal value as a stopgap. fixes #247 
**Changelog**
:cl:
- fix: MKCs will now properly be unconscious when at low-power mode
- fix: plastic and oilpacks can be applied to MKCs again. be warned, the empty application bug will still occur if the MKC has caustic damage present when using these items; a more comprehensive fix is hopefully coming soon

fix: post-upstream merge mkc hotfixes

---

Resources/Prototypes/Entities/Structures/Machines/telecomms.yml
Resources/Prototypes/_starcup/Roles/Jobs/Wildcards/prisoner.yml

Adds the prisoner key to the security telecom server and removes the common key from the prisoner telecom server.
Fixes https://github.com/teamstarcup/starcup/issues/269. 
No other specific telecom server has the common key, prisoner shouldn't either. 
**Changelog**
:cl:
- fix: Prisoner comms should now be available on all maps.

fix: security/prisoner telecom server fixes

---

Resources/Locale/en-US/_starcup/preferences/loadout-groups.ftl
Resources/Prototypes/Loadouts/loadout_groups.yml
Resources/Prototypes/Loadouts/role_loadouts.yml
Resources/Prototypes/Roles/Jobs/Civilian/musician.yml
Resources/Prototypes/Roles/Jobs/Command/captain.yml
Resources/Prototypes/Roles/Jobs/Security/detective.yml
Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
Resources/Prototypes/Roles/Jobs/Security/warden.yml
Resources/Prototypes/_DV/Loadouts/role_loadouts.yml
Resources/Prototypes/_DV/Roles/Jobs/Command/administrative_assistant.yml
Resources/Prototypes/_starcup/Loadouts/Jobs/Civilian/bartender.yml
Resources/Prototypes/_starcup/Loadouts/Jobs/Command/command_shared.yml
Resources/Prototypes/_starcup/Loadouts/Jobs/Science/roboticist.yml
Resources/Prototypes/_starcup/Loadouts/Jobs/Security/security_officer.yml
Resources/Prototypes/_starcup/Loadouts/Miscellaneous/glasses.yml
Resources/Prototypes/_starcup/Loadouts/loadout_groups.yml

adds the eyepatch to the generic glasses loadout that basically everyone gets, and also adds a bunch of new departmental loadouts that allow for selection of different glasses/eyepatches!
eyepatches as a character creation option introduces fun roleplaying opportunities, and allow for more versatility than the gauze eyepatch markings might on their own. also some command/sec players might like the one-eyed visor look over the glasses look and that would be nice to support
**Changelog**
:cl:
- add: departmental glasses loadouts for security and command, plus options for bartender, roboticist, and musician
- add: standard eyepatches are now in the generic glasses loadout group

feat: eyepatch/glasses loadouts

---

Resources/Maps/_starcup/byoin.yml

adds the salvage job board, the mnk drobe, and updates all the new access levels for byoin
**Changelog**
:cl:
- tweak: the new access levels for the psychologist, librarian, and boxer have been implemented into byoin
- add: mnk drobe added to byoin
- fix: salvage job board added to byoin

map(byoin): access levels, new items

---

Content.Shared/_CD/Records/PlayerProvidedCharacterRecords.cs

Fixes #303
Bugfix for characters exported earlier or from servers that don't have admin records
Provided default value for adminrecords.
Decided to provide this as a quick fix rather than a deeper look into the CD code to ensure further safety at this time.
**Changelog**
:cl:
- fix: Characters without admin records should import now

fix: Adds default value to AdminEntries

---

Resources/Prototypes/Entities/Structures/Wallmounts/Signs/bar_sign.yml
Resources/Prototypes/Entities/Structures/Wallmounts/Signs/base_structuresigns.yml
Resources/Prototypes/Entities/Structures/Wallmounts/Switches/switch.yml
Resources/Prototypes/Entities/Structures/Wallmounts/base_wallmount.yml

Early upstream merge for https://github.com/space-wizards/space-station-14/pull/39425 and https://github.com/space-wizards/space-station-14/pull/39487. Fixes wall signs and buttons necessarily being anchored, which would center them in the tile. (Thanks to Pengy for finding these.)
We got the problem in the upstream merge and not the fix, and unfortunately rebranding ops caused a lot of the maps to be loaded then saved. Might be worthwhile redoing the changes rebranding ops made since that might be less work than redoing every sign.
**Changelog**
Not player-facing.

fix: sign and button centering fix

---

Resources/Maps/_starcup/loop.yml
Resources/Maps/_starcup/omega.yml
Resources/Maps/_starcup/train.yml
Resources/Migrations/syndicate-migrations.yml
Resources/Prototypes/_starcup/Catalog/Fills/Lockers/suit_storage.yml

creates a new fill prototype for the new syndicate captain's hardsuit, and replaces the old versions from loop, omega, and train with it
I forgot
**Changelog**
:cl:
- fix: loop, omega, and train should now have the correct captain's hardsuit mapped

fix: syndicate captain hardsuit storage

---

Resources/Prototypes/Entities/Clothing/Hands/colored.yml

puts an engineering contraband label on insulated gloves
you can view an extensive community discussion on the topic on our forum [here](https://forum.starcup.cc/t/insuls-and-doorhacking-discussion-on-the-merits-of-being-in-places-youre-not-supposed-to-be/196), but the short of it is: insulated gloves are designed to let you and encourage you to do crimes, and doorhacking needs to be taken more seriously if we want to commit to the standard of roleplaying that starcup is trying to encourage. people having insuls when they shouldn't should not be considered normal
jury's still out on budget insuls. those are in a weird spot. we'll see how this goes first
**Changelog**
:cl:
- tweak: insulated gloves are now labeled as engineering contraband. doorhackers take caution

tweak: make insuls engineering contraband (without the mapping changes)

---

Resources/Prototypes/_starcup/Loadouts/Miscellaneous/glasses.yml
Resources/Prototypes/_starcup/Loadouts/loadout_groups.yml

The right-side patch was on there so why not the left?
**Changelog**
:cl:
- add: Added flipped eyepatches to loadouts alongside regular eyepatches.

feat: add flipped eyepatch to loadouts

---

Resources/Prototypes/_starcup/Maps/banana.yml

I accidentally gave Banana the evac shuttle as the cargo shuttle.
**Changelog**
:cl:
- fix: Banana now has a cargo shuttle.

fix: cargo shuttle for banana

---

Resources/Prototypes/GameRules/meteorswarms.yml
Resources/Prototypes/_starcup/Entities/Objects/Weapons/Guns/Projectiles/meteors.yml
Resources/Prototypes/_starcup/GameRules/meteorswarms.yml

Space Dust now deals significantly less damage (both on impact and for the explosion) and won't occur within the first 10 minutes of the round starting. Additionally, the gag meteors (Urists, Clowns, Potatoes, etc) have been disabled to fit in with the tone of the server.
Space Dust events have been causing issues for a while now due to their destructive power, overwhelming engineers with structural damage and spacings and leading to player burnout. Currently, Space Dust meteors deal 100 Blunt damage on impact and then explode in a 3x3 pattern which deals 25 Blunt, 25 Pierce, and 25 Heat to the center tile. Both the initial impact and the explosion deal enough damage to shatter reinforced windows, causing significant spacing issues with relative frequency. Because some parts of the …

tweak: meteor rebalancing pass

---

Resources/Prototypes/_starcup/Entities/Objects/Weapons/Guns/Projectiles/meteors.yml

My previous PR overwrote the new Space Dust prototype's Destructible component entirely rather than overwriting only the variable adjusted. This meant the new meteor would not be destroyed on contact with an entity, but would instead deal 25 Blunt continuously to it and never despawn or explode. This PR fixes that behavior.
Additionally, I've given the new prototype a name to make it easier to differentiate from the old Space Dust prototype in the Entity Spawn Menu.
Added the Destruction, Play Sound, and Explode behaviors to the Destructible component's Damage Trigger. This is effectively a copy-paste of the original prototype's code, but it's necessary to make the new prototype function.
**Changelog**
:cl:
- fix: space dust explodes on contact

fix: space dust explodes on contact

---

Content.Server/Chemistry/Components/VaporComponent.cs
Content.Server/Chemistry/EntitySystems/VaporSystem.cs

CleanDecalsReaction appears to be very costly. A temporary embargo has been placed on space cleaner in our live rounds over it. I have no way of gathering traces with enough granularity to figure it out exactly, but we're already attempting to cache previous tile reactions in a way that definitely does not work. This change improves that in with the hope that the performance cost becomes negligible.
**Changelog**
:cl:
- fix: Hopefully improved space cleaner-related lag.

perf: track all previous tiles for vapor entities

---

Resources/Migrations/starcup-migrations.yml

Random lockbox spawner seems to have been missed in https://github.com/teamstarcup/starcup/pull/328, this adds it; there was one mapped on Reach I noticed. 
If there's some reason to avoid using migrations on spawners/this was purposefully excluded then let me know.

fix: add random lockbox spawner to migrations

---

Resources/clientCommandPerms.yml

The `warp` command did not have a permission flag until now. You need `AdminFlags.ADMIN` to use it.
**Changelog**

fix: add warp command permission

---

Resources/engineCommandPerms.yml

The `pos` command was lacking a permission flag. This sets it to `DEBUG`.
**Changelog**

fix: pos command perm

---

Content.Shared/Decals/SharedDecalSystem.cs

Decals are somewhat heavy to serialize and networking 2400 decals in 105 KB synchronously to a bunch of players across entirely exclusive potentially visible sets is fantastically infeasible.
**Changelog**
:cl:
- tweak: Hopefully mitigated decal-related lag by shrinking chunk sizes.

tweak: shrink decal chunk size from 32 to 8

---

Resources/Locale/en-US/_starcup/prototypes/access/accesses.ftl
Resources/Prototypes/Entities/Objects/Tools/access_configurator.yml

quick hotfix cuz I forgot to give the base access configurator the new brigmedic access, also forgot to give the universal configurator any of them because I didn't realize you needed to do that
also fixes a typo in the ftl file that made the combat medic's access level display incorrectly oops
**Changelog**
:cl:
- fix: the access configurator has had missing access levels added
- fix: the combat medic's access level now displays its name properly

fix: give access configurators the new access levels

---

Content.Shared/Physics/CollisionGroup.cs
Resources/Prototypes/Entities/Structures/Wallmounts/base_wallmount.yml

gives the base wallmount prototype a physics fixture so wallmounts can be interacted with from across tables/counters/etc. soft port of [wizden#38802](https://redirect.github.com/space-wizards/space-station-14/pull/38802)
the standard interact range should be 1.5 tiles, but there are a variety of situations as illustrated in [wizden#37741](https://redirect.github.com/space-wizards/space-station-14/issues/37741) where it gets shortened for some inexplicable reason; thus, the fact that you can't interact with wallmounts across tables and the like is fully a bug
this makes life very difficult for many reasons and creates a bunch of really finicky annoying mapping constraints for things like fire alarms, apcs, and shelves. this should allow for much, much greater flexibility in layouts and …

fix: extend wallmount interact distance

---

Content.Shared/BarSign/BarSignPrototype.cs
Content.Shared/BarSign/BarSignSystem.cs
Resources/Prototypes/Entities/Structures/Wallmounts/Signs/bar_sign.yml
Resources/Prototypes/bar_signs.yml

Make bar signs emit light.
Since each sign variant can have different colors, the color of the emitted light is set in each BarSignPrototype instance.
Known issues:
- light color does not function well with animations that change their primary color
Complements #413 
**Changelog**
:cl:
- add: Bar signs now emit light.

feat: bar signs emit light

---

Resources/Prototypes/Catalog/Fills/Lockers/service.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/bardrobe.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/boozeomat.yml
Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
Resources/Prototypes/_starcup/Catalog/Fills/Lockers/service.yml

renames the "booze storage" cabinet to "bartender's cabinet" and rewrites its description, relocates the armor vest and bandolier from the bardrobe into it, removes everything else, and places the damp rag and hand labeler into the booze-o-mat
also adds a new filled prototype without the gun in it, in case mappers want to use the filled version of the bartender shotgun cabinet I made a little while back
first off, it's not _booze_ storage! there's no booze in it! the beer bottles don't even have beer in them!!!
also it has confusingly redundant contents, with most of it being available from the booze-o-mat or bardrobe, which are usually pretty much right next to the cabinet. I think it makes most sense for it, being an id-locked storage unit, to be where the bartender's specialized combat …

tweak: move bartender's combat gear to cabinet (and rename it)

---

Content.Server/_DV/Mail/EntitySystems/MailSystem.cs

Nyano code no longer generates test failures from `_log.Error` when attempting to create mail when nobody is around.
**Changelog**
snore

fix: test failures from mail teleports

---

Resources/Prototypes/Loadouts/Miscellaneous/survival.yml

Survival box loadouts are split by species due to some having unique needs, such as nitrogen instead of oxygen or cotton-based food instead of a standard PSB. Notably, the Mime job has its own species list due to mime survival boxes having a croissant by default upstream, and it seems we didn't update this list properly to include new species.
Whoops.
Currently, half our species start with a survival box as a mime and half don't. That's obviously not intended and needs to be fixed.
**Changelog**
:cl:
- fix: all mimes now start with a survival box

fix: all mimes now start with a survival box

---

Resources/Prototypes/Entities/Mobs/NPCs/pets.yml

removes the telecrystal drop from butchering renault, and also adds the `SentienceTarget` component so she can be targeted by sentience events.
in addition to just kinda being a gigantic tone-lurching bummer that you're incentivized to carve up the cute fox, the telecrystal thing feels very inside baseball in a way that I'm not a fan of; there shouldn't be a secret bonus objectives every traitor basically has but that no one gets told about. that's not fun
the sentience thing is because foxcurl asked me to very nicely
**Changelog**
:cl:
- remove: butchering renault no longer gives additional telecrystals
- feat: renault can now be targeted by random sentience events

tweak: remove tc drop from renault, let her become sentient

---

Resources/Prototypes/Reagents/Consumable/Drink/alcohol.yml

very slightly increases the ethanol numbers on cocktails that use absinthe as an ingredient (except for bacchus's, whose ethanol content is nonsensical on purpose). this specifically affects monkey business, death in the afternoon, and the sun always rises
[wizden#34371](https://redirect.github.com/space-wizards/space-station-14/pull/34371) effectively gave absinthe an extra 0.05 ethanol content, and so this ensures cocktails' proportionality with their component ingredients' ethanol contents as per #204! these might be very small numbers-wise, but with ethanol, very slight nudges can possibly come up!
**Changelog**
:cl:
- tweak: cocktails with absinthe (except bacchus's) have had their ethanol content very, very slightly increased to match absinthe's slight bump in ethanol

tweak: nudge up ethanol contents of absinthe cocktails

---

Resources/Prototypes/_starcup/Entities/Objects/Specific/chemistry-bottles.yml

Added an autofill 30u bottle of ammonia, so ammonia bottles can be mapped to areas.
It is advantageous to allow prisoners to access ammonia, as it and ethanol can give them access to some largely harmless chemistry, but the ingredients to make ammonia are too volatile to offer them.
**Changelog**
:cl:
- tweak: added ammonia bottle

feat: add ammonia bottle

---

Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml

Cyborgs are opened with the screwdriver after being unlocked. 
This is the muscle memory of most of our roboticists, and the vast majority of other panels in the game use screwdrivers. 
Upstream introduced the change in https://github.com/space-wizards/space-station-14/pull/32796, and as far as I can tell the only rationale here is "thing ss13 does" (not a good reason) and "eventually we might add another hacking panel," except it makes more sense to use the screwdriver for the legal panel and a crowbar to access the hacking panel.
**Changelog**
:cl:
- tweak: Cyborg panels are opened with screwdrivers again.

tweak: borgs are opened with screwdrivers again

---

Resources/Prototypes/Loadouts/role_loadouts.yml

Fix for #473, atmos head loadout group was missing from the role loadout.
**Changelog**
:cl:
- fix: Atmos beret is now selectable for atmos technician loadouts.

fix: add atmos tech head loadoutgroup to atmos role loadout

---

Resources/Migrations/starcup-migrations.yml
Resources/Prototypes/Entities/Markers/Spawners/Random/posters.yml
Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml

removes prototypes for posters that have been migrated out, and also brings back the beach star yamamoto poster with a rewritten description
keeping the map prototypes around despite being removed via migrations risks mapper confusion, so I just commented them out so they won't show in the spawn menu at all
also people keep wanting to use the silly anime poster so I brought back the silly anime poster
**Changelog**
not player facing, no cl

tweak: remove unused poster prototypes, bring back the anime poster
